FIND_PATH(UVW_INCLUDE_DIR NAMES uvw.hpp)

FIND_LIBRARY(UVW_LIBRARY uvw)
get_filename_component(UVW_LIBRARY_DIR ${UVW_LIBRARY} PATH)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(uvw DEFAULT_MSG
  UVW_INCLUDE_DIR
  UVW_LIBRARY
  UVW_LIBRARY_DIR)

mark_as_advanced(
  UVW_INCLUDE_DIR
  UVW_LIBRARY_DIR
  UVW_LIBRARY)

