name: Autobuild for Windows

on: [push, workflow_dispatch, repository_dispatch]

env:
  CMAKE_PREFIX_PATH: "$GITHUB_WORKSPACE/libraries/openssl;$GITHUB_WORKSPACE/libraries/zstd;$GITHUB_WORKSPACE/libraries/mongoc;$GITHUB_WORKSPACE/libraries/mongocxx;$GITHUB_WORKSPACE/libraries/libuv;$GITHUB_WORKSPACE/libraries/yaml;"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout OpenSSL
        uses: actions/checkout@v3
        with:
          repository: "darktohka/openssl"
          ref: "feature/add-no-apps"
          path: "openssl"
      - name: Download Jom
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://download.qt.io/official_releases/jom/unstable-jom.zip"
          target: openssl/
      - name: Unpack Jom
        shell: bash
        working-directory: openssl
        run: >
          unzip -qq unstable-jom.zip
      - name: Configure OpenSSL
        shell: powershell
        working-directory: openssl
        run: >
          perl configure VC-WIN64A no-asm no-shared no-tests no-module no-dso no-legacy no-apps `
            --prefix="${{ github.workspace }}\libraries\openssl" --openssldir="${{ github.workspace }}\libraries\openssl" /FS
      - name: Build and install OpenSSL
        shell: powershell
        working-directory: openssl
        run: >
          ./jom install_sw
      - name: Checkout mongo-c-driver
        uses: actions/checkout@v3
        with:
          repository: "mongodb/mongo-c-driver"
          ref: "master"
          path: "mongo-c-driver"
      - name: Setup mongo-c-driver
        working-directory: ./mongo-c-driver-master
        shell: powershell
        run: >
          cmake -G"Visual Studio 17 2022" -A x64 -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/mongoc" `
            -DENABLE_STATIC=ON -DENABLE_ZLIB=BUNDLED -DENABLE_ZSTD=OFF -DENABLE_SNAPPY=OFF -DENABLE_SASL=OFF `
            -DENABLE_SSL=OPENSSL -DENABLE_MONGODB_AWS_AUTH=OFF -DENABLE_EXTRA_ALIGNMENT=OFF -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF `
            .
      - name: Compile mongo-c-driver
        working-directory: ./mongo-c-driver-master
        shell: powershell
        run: |
          cmake --build . --config Release
      - name: Checkout code
        uses: actions/checkout@v3
