name: Autobuild for Windows

on: [push, workflow_dispatch, repository_dispatch]

env:
  CMAKE_PREFIX_PATH: "${{ github.workspace }}\\libraries\\openssl;${{ github.workspace }}\\libraries\\zstd;${{ github.workspace }}\\libraries\\mongoc;${{ github.workspace }}\\libraries\\mongocxx;${{ github.workspace }}\\libraries\\libuv;${{ github.workspace }}\\libraries\\yaml;${{ github.workspace }}\\libraries"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Query third party commits
        id: query
        shell: bash
        run: |
          echo "::set-output name=MONGOC_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=MONGOCXX_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-cxx-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=OPENSSL_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/openssl/commits/feature/add-no-apps | jq -r .sha)" && \
          echo "::set-output name=MONGOC_VERSION::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/releases | jq -r .[0].tag_name)"
      - name: Cache OpenSSL
        id: cache-openssl
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/openssl
          key: ${{ runner.os }}-openssl-${{ steps.query.outputs.OPENSSL_COMMIT }}
      - name: Cache mongo-c-driver
        id: cache-mongoc
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongoc
          key: ${{ runner.os }}-${{ steps.query.outputs.OPENSSL_COMMIT }}-${{ steps.query.outputs.MONGOC_COMMIT }}
      - name: Cache mongo-cxx-driver
        id: cache-mongocxx
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongocxx
          key: ${{ runner.os }}-mongocxx-${{ steps.query.outputs.MONGOCXX_COMMIT }}
      - name: Checkout OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "darktohka/openssl"
          ref: "feature/add-no-apps"
          path: "openssl"
      - name: Download Jom
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://download.qt.io/official_releases/jom/unstable-jom.zip"
          target: openssl/
      - name: Unpack Jom
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: bash
        working-directory: openssl
        run: >
          unzip -qq unstable-jom.zip
      - name: Configure OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: powershell
        working-directory: openssl
        run: >
          perl configure VC-WIN64A no-asm no-shared no-tests no-module no-dso no-legacy no-apps `
            --prefix="${{ github.workspace }}\libraries\openssl" --openssldir="${{ github.workspace }}\libraries\openssl" /FS
      - name: Build and install OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: powershell
        working-directory: openssl
        run: >
          ./jom install_sw
      - name: Checkout mongo-c-driver
        if: steps.cache-mongoc.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "mongodb/mongo-c-driver"
          ref: "master"
          path: "mongo-c-driver"
      - name: Setup mongo-c-driver
        if: steps.cache-mongoc.outputs.cache-hit != 'true'
        working-directory: ./mongo-c-driver
        shell: powershell
        run: >
          cmake -G"Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" `
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/mongoc" `
            -DCMAKE_CXX_STANDARD=17 -DBUILD_VERSION="${{ steps.query.outputs.MONGOC_VERSION }}" `
            -DENABLE_STATIC=ON -DENABLE_ZLIB=BUNDLED -DENABLE_ZSTD=OFF -DENABLE_SNAPPY=OFF -DENABLE_SASL=OFF `
            -DENABLE_SSL=OPENSSL -DENABLE_MONGODB_AWS_AUTH=OFF -DENABLE_EXTRA_ALIGNMENT=OFF -DENABLE_TESTS=OFF -DENABLE_EXAMPLES=OFF `
            .
      - name: Build and install mongo-c-driver
        if: steps.cache-mongoc.outputs.cache-hit != 'true'
        working-directory: ./mongo-c-driver
        shell: powershell
        run: >
          cmake --build . --target install --config Release
      - name: Checkout mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "mongodb/mongo-cxx-driver"
          ref: "master"
          path: "mongo-cxx-driver"
      - name: Cleanup mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        shell: bash
        working-directory: mongo-cxx-driver
        run: |
          for dir in "benchmark docs examples" do; rm -rf $dir; mkdir -p $dir; touch $dir/CMakeLists.txt; done
      - name: Setup mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        working-directory: ./mongo-cxx-driver
        shell: powershell
        run: >
          cmake -G"Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" `
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/mongocxx" `
            -DCMAKE_CXX_STANDARD=17 -DBUILD_VERSION="${{ steps.query.outputs.MONGOC_VERSION }}" `
            -DBUILD_SHARED_LIBS=OFF -DENABLE_UNINSTALL=OFF -DENABLE_TESTS=OFF `
            .
      - name: Build and install mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        working-directory: ./mongo-cxx-driver
        shell: powershell
        run: >
          cmake --build . --target install --config Release