name: Autobuild for Windows

on: [push, workflow_dispatch, repository_dispatch]

env:
  CMAKE_PREFIX_PATH: "${{ github.workspace }}\\libraries\\sqlite;${{ github.workspace }}\\libraries\\bison;${{ github.workspace }}\\libraries\\uvw;${{ github.workspace }}\\libraries\\boost;${{ github.workspace }}\\libraries\\openssl;${{ github.workspace }}\\libraries\\soci;${{ github.workspace }}\\libraries\\mongoc;${{ github.workspace }}\\libraries\\mongocxx;${{ github.workspace }}\\libraries\\libuv;${{ github.workspace }}\\libraries\\yaml;${{ github.workspace }}\\libraries"

jobs:
  build:
    strategy:
      matrix:
        os:
        - windows-latest
    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.os }}
    steps:
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Query third party commits
        id: query
        shell: bash
        run: |
          echo "::set-output name=MONGOC_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=MONGOCXX_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-cxx-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=OPENSSL_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/openssl/commits/feature/add-no-apps | jq -r .sha)" && \
          echo "::set-output name=LIBUV_COMMIT::$(curl -sS https://api.github.com/repos/libuv/libuv/commits/v1.x | jq -r .sha)" && \
          echo "::set-output name=UVW_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/uvw/commits/patch-1 | jq -r .sha)" && \
          echo "::set-output name=YAML_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/yaml-cpp/commits/patch-1 | jq -r .sha)" && \
          echo "::set-output name=SOCI_COMMIT::$(curl -sS https://api.github.com/repos/soci/soci/commits/master | jq -r .sha)" && \
          echo "::set-output name=MONGOC_VERSION::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/releases | jq -r .[0].tag_name)" && \
          FLEXBISON_REPLY="$(curl -Ss https://api.github.com/repos/lexxmark/winflexbison/releases)" && \
          echo "::set-output name=FLEXBISON_BUILD_ID::$(echo $FLEXBISON_REPLY | jq -r .[0].assets[0].id)" && \
          echo "::set-output name=FLEXBISON_LINK::$(echo $FLEXBISON_REPLY | jq -r .[0].assets[0].browser_download_url)" && \
          SQLITE_FILENAME="$(curl -Ss https://sqlite.org/download.html | sed -nE "s/^PRODUCT,.*UTC,(.*),.*,.*$/\1/p")" && \
          echo "::set-output name=SQLITE_FILENAME::$SQLITE_FILENAME" && \
          echo "::set-output name=SQLITE_HASH::$(echo "$SQLITE_FILENAME" | sha256sum | cut -d ' ' -f 1)"
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.2
        with:
          key: ${{ matrix.os }}-ccache
      - name: Cache OpenSSL
        id: cache-openssl
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/openssl
          key: ${{ runner.os }}-openssl-${{ steps.query.outputs.OPENSSL_COMMIT }}
      - name: Cache mongo-c-driver
        id: cache-mongoc
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongoc
          key: ${{ runner.os }}-mongoc-${{ steps.query.outputs.OPENSSL_COMMIT }}-${{ steps.query.outputs.MONGOC_COMMIT }}
      - name: Cache mongo-cxx-driver
        id: cache-mongocxx
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongocxx
          key: ${{ runner.os }}-mongocxx-${{ steps.query.outputs.OPENSSL_COMMIT }}-${{ steps.query.outputs.MONGOC_COMMIT }}-${{ steps.query.outputs.MONGOCXX_COMMIT }}
      - name: Cache libuv
        id: cache-libuv
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/libuv
          key: ${{ runner.os }}-uv-${{ steps.query.outputs.LIBUV_COMMIT }}
      - name: Cache uvw
        id: cache-uvw
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/uvw
          key: ${{ runner.os }}-uvw-${{ steps.query.outputs.LIBUV_COMMIT }}-${{ steps.query.outputs.UVW_COMMIT }}
      - name: Cache yaml-cpp
        id: cache-yaml
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/yaml
          key: ${{ runner.os }}-yaml-${{ steps.query.outputs.YAML_COMMIT }}
      - name: Cache SQLite3
        id: cache-sqlite
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/sqlite
          key: ${{ runner.os }}-sqlite-${{ steps.query.outputs.SQLITE_HASH }}
      - name: Cache SOCI
        id: cache-soci
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/soci
          key: ${{ runner.os }}-soci2-${{ steps.query.outputs.SQLITE_HASH }}-${{ steps.query.outputs.SOCI_COMMIT }}
      - name: Cache Bison and Flex
        id: cache-bison
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/bison
          key: ${{ runner.os }}-bison-${{ steps.query.outputs.FLEXBISON_BUILD_ID }}
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/boost
          key: ${{ runner.os }}-boost2
      - name: Checkout OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "darktohka/openssl"
          ref: "feature/add-no-apps"
          path: "openssl"
      - name: Download Jom
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://download.qt.io/official_releases/jom/unstable-jom.zip"
          target: openssl/
      - name: Unpack Jom
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: bash
        working-directory: openssl
        run: >
          unzip -qq unstable-jom.zip
      - name: Configure OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: bash
        working-directory: openssl
        run: >
          perl configure VC-WIN64A no-asm no-shared no-tests no-module no-dso no-legacy no-apps `
            --prefix="${{ github.workspace }}/libraries/openssl" --openssldir="${{ github.workspace }}/libraries/openssl" /FS
      - name: Build and install OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: powershell
        working-directory: openssl
        run: >
          ./jom install_sw
      - name: Checkout mongo-c-driver
        if: steps.cache-mongoc.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "mongodb/mongo-c-driver"
          ref: "master"
          path: "mongo-c-driver"
      - name: Setup mongo-c-driver
        if: steps.cache-mongoc.outputs.cache-hit != 'true'
        working-directory: ./mongo-c-driver
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/mongoc" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_STANDARD=23 \
            -DBUILD_VERSION="${{ steps.query.outputs.MONGOC_VERSION }}" \
            -DENABLE_STATIC=ON -DENABLE_ZLIB=BUNDLED -DENABLE_ZSTD=OFF -DENABLE_SNAPPY=OFF -DENABLE_SASL=OFF \
            -DENABLE_SSL=OPENSSL -DENABLE_MONGODB_AWS_AUTH=OFF -DENABLE_EXTRA_ALIGNMENT=OFF -DENABLE_TESTS=OFF \
            -DENABLE_EXAMPLES=OFF .
      - name: Build and install mongo-c-driver
        if: steps.cache-mongoc.outputs.cache-hit != 'true'
        working-directory: ./mongo-c-driver
        shell: powershell
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Checkout mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "mongodb/mongo-cxx-driver"
          ref: "master"
          path: "mongo-cxx-driver"
      - name: Cleanup mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        shell: bash
        working-directory: mongo-cxx-driver
        run: |
          for dir in benchmark docs examples; do rm -rf $dir; mkdir -p $dir; touch $dir/CMakeLists.txt; done
      - name: Setup mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        working-directory: ./mongo-cxx-driver
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/mongocxx" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/Zc:__cplusplus /EHsc" \
            -DCMAKE_CXX_STANDARD=23 -DBUILD_VERSION="${{ steps.query.outputs.MONGOC_VERSION }}" \
            -DBUILD_SHARED_LIBS=OFF -DENABLE_UNINSTALL=OFF -DENABLE_TESTS=OFF \
            .
      - name: Build and install mongo-cxx-driver
        if: steps.cache-mongocxx.outputs.cache-hit != 'true'
        working-directory: ./mongo-cxx-driver
        shell: powershell
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Checkout libuv
        if: steps.cache-libuv.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "libuv/libuv"
          ref: "v1.x"
          path: "libuv"
      - name: Setup libuv
        if: steps.cache-libuv.outputs.cache-hit != 'true'
        working-directory: ./libuv
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/libuv" \
            -DCMAKE_C_STANDARD=23 -DLIBUV_BUILD_TESTS=OFF -DLIBUV_BUILD_BENCH=OFF .
      - name: Build and install libuv
        if: steps.cache-libuv.outputs.cache-hit != 'true'
        working-directory: ./libuv
        shell: powershell
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Checkout uvw
        if: steps.cache-uvw.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "darktohka/uvw"
          ref: "patch-1"
          path: "uvw"
      - name: Setup uvw
        if: steps.cache-uvw.outputs.cache-hit != 'true'
        working-directory: uvw/build
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/uvw" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/Zc:__cplusplus /EHsc" \
            -DCMAKE_CXX_STANDARD=23 -DBUILD_UVW_SHARED_LIB=OFF -DBUILD_UVW_LIBS=ON \
            -DBUILD_TESTING=OFF -DBUILD_DOCS=OFF -DFETCH_LIBUV=OFF -DFIND_LIBUV=ON ..
      - name: Build and install uvw
        if: steps.cache-uvw.outputs.cache-hit != 'true'
        working-directory: uvw/build
        shell: powershell
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Checkout yaml-cpp
        if: steps.cache-yaml.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "darktohka/yaml-cpp"
          ref: "patch-1"
          path: "yaml"
      - name: Setup yaml-cpp
        if: steps.cache-yaml.outputs.cache-hit != 'true'
        working-directory: yaml
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/yaml" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/Zc:__cplusplus /EHsc" \
            -DCMAKE_CXX_STANDARD=23 -DYAML_CPP_BUILD_CONTRIB=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_BUILD_SHARED_LIBS=OFF \
            -DYAML_CPP_FORMAT_SOURCE=OFF -DYAML_CPP_BUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF \
            .
      - name: Build and install yaml-cpp
        if: steps.cache-yaml.outputs.cache-hit != 'true'
        working-directory: yaml
        shell: powershell
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Download SQLite3
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        uses: suisei-cn/actions-download-file@v1
        with:
          url: https://sqlite.org/${{ steps.query.outputs.SQLITE_FILENAME }}
          target: sqlite/
      - name: Extract SQLite3
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        shell: bash
        working-directory: sqlite
        run: |
          tar -xzf *.tar.gz && rm -f *.tar.gz && mv sqlite-snapshot-* src
      - name: Create SQLite3 project
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        shell: bash
        working-directory: sqlite
        run: >
          cat <<EOF > CMakeLists.txt
            PROJECT(sqlite3)
            cmake_minimum_required(VERSION 3.10)

            include_directories(${CMAKE_SOURCE_DIR}/src)
            add_library(sqlite3 STATIC src/sqlite3.c src/sqlite3.h src/sqlite3ext.h)

            add_definitions(-DSQLITE_ENABLE_RTREE)
            add_definitions(-DSQLITE_ENABLE_FTS4)
            add_definitions(-DSQLITE_ENABLE_FTS5)
            add_definitions(-DSQLITE_ENABLE_JSON1)
            add_definitions(-DSQLITE_ENABLE_RBU)
            add_definitions(-DSQLITE_ENABLE_STAT4)

            install(FILES src/sqlite3.h src/sqlite3ext.h DESTINATION include)
            install(TARGETS sqlite3 LIBRARY DESTINATION lib ARCHIVE DESTINATION lib)
          EOF
      - name: Setup SQLite3
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        working-directory: sqlite
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/sqlite" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_STANDARD=23 .
      - name: Build and install SQLite3
        if: steps.cache-sqlite.outputs.cache-hit != 'true'
        working-directory: sqlite
        shell: powershell
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Checkout SOCI
        if: steps.cache-soci.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "SOCI/soci"
          ref: "master"
          path: "soci"
      - name: Setup SOCI
        if: steps.cache-soci.outputs.cache-hit != 'true'
        working-directory: soci
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/soci" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/Zc:__cplusplus /EHsc" \
            -DCMAKE_CXX_STANDARD=23 -DSOCI_SHARED=OFF -DSOCI_TESTS=OFF \
            .
      - name: Build and install SOCI
        if: steps.cache-soci.outputs.cache-hit != 'true'
        working-directory: soci
        shell: powershell
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Fix SOCI library names
        if: steps.cache-soci.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/libraries/soci/lib
        shell: bash
        run: |
          for file in $(find . -name "*_*_*.*"); do mv "$file" "${file//_[0-9]}"; done
      - name: Download Bison and Flex
        if: steps.cache-bison.outputs.cache-hit != 'true'
        uses: suisei-cn/actions-download-file@v1
        with:
          url: ${{ steps.query.outputs.FLEXBISON_LINK }}
          target: ${{ github.workspace }}/libraries/bison
      - name: Unzip Bison and Flex
        if: steps.cache-bison.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{ github.workspace }}/libraries/bison
        run: |
          unzip -qq *.zip && rm -f *.zip
      - name: Create Boost folder
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        working-directory: ${{ github.workspace }}
        run: >
          mkdir -p boost/boost/built libraries/boost/include libraries/boost/cmake
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        uses: MarkusJx/install-boost@v2.3.0
        with:
          boost_version: "1.79.0"
          boost_install_dir: "${{ github.workspace }}"
          platform_version: 2022
          toolset: msvc
      - name: Fix Boost folder
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        working-directory: boost/boost
        run: |
          rm -rf boost && cp -r include/boost .
      - name: Build Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: powershell
        working-directory: boost/boost
        run: >
          ./bootstrap.bat; ./b2 tools/bcp; ./dist/bin/bcp icl built
      - name: Package Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        working-directory: boost/boost/built
        run: |
          mv boost "${{ github.workspace }}/libraries/boost/include/" && cp ../tools/cmake/include/*.cmake "${{ github.workspace }}/libraries/boost/cmake/" && find "${{ github.workspace }}/libraries/boost"
      - name: Checkout Astron
        uses: actions/checkout@v3
        with:
          path: "Astron"
      - name: Setup Astron
        working-directory: Astron/build
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/build/astron" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/Zc:__cplusplus /EHsc" \
            -DCMAKE_CXX_STANDARD=23 \
            -DCMAKE_EXE_LINKER_FLAGS="/alternatename:__imp___std_init_once_complete=__imp_InitOnceComplete /alternatename:__imp___std_init_once_begin_initialize=__imp_InitOnceBeginInitialize" \
            ..
      - name: Build and install Astron
        working-directory: Astron/build
        shell: bash
        run: >
          cmake --build . --parallel 2 --target install --config Release
      - name: Upload Astron
        uses: actions/upload-artifact@v3
        with:
          name: astron-windows
          path: ${{ github.workspace }}/build/astron/bin/astrond.exe
      - name: Package libraries
        shell: bash
        run: |
          tar -axf astron-libraries.tar.zst libraries
      - name: Upload libraries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-libraries
          path: astron-libraries.tar.zst