name: Autobuild for Windows

on: [push, workflow_dispatch, repository_dispatch]

env:
  CMAKE_PREFIX_PATH: "${{ github.workspace }}\\libraries\\sqlite;${{ github.workspace }}\\libraries\\bison;${{ github.workspace }}\\libraries\\uvw;${{ github.workspace }}\\libraries\\boost;${{ github.workspace }}\\libraries\\openssl;${{ github.workspace }}\\libraries\\soci;${{ github.workspace }}\\libraries\\mongoc;${{ github.workspace }}\\libraries\\mongocxx;${{ github.workspace }}\\libraries\\libuv;${{ github.workspace }}\\libraries\\yaml;${{ github.workspace }}\\libraries"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            cxx_flags: ""
    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.os }}
    steps:
      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
      - name: Query third party commits
        id: query
        shell: bash
        run: |
          echo "::set-output name=MONGOC_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=MONGOCXX_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-cxx-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=OPENSSL_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/openssl/commits/feature/add-no-apps | jq -r .sha)" && \
          echo "::set-output name=LIBUV_COMMIT::$(curl -sS https://api.github.com/repos/libuv/libuv/commits/v1.x | jq -r .sha)" && \
          echo "::set-output name=UVW_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/uvw/commits/patch-1 | jq -r .sha)" && \
          echo "::set-output name=YAML_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/yaml-cpp/commits/patch-1 | jq -r .sha)" && \
          echo "::set-output name=SOCI_COMMIT::$(curl -sS https://api.github.com/repos/soci/soci/commits/master | jq -r .sha)" && \
          echo "::set-output name=MONGOC_VERSION::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/releases | jq -r .[0].tag_name)" && \
          FLEXBISON_REPLY="$(curl -Ss https://api.github.com/repos/lexxmark/winflexbison/releases)" && \
          echo "::set-output name=FLEXBISON_BUILD_ID::$(echo $FLEXBISON_REPLY | jq -r .[0].assets[0].id)" && \
          echo "::set-output name=FLEXBISON_LINK::$(echo $FLEXBISON_REPLY | jq -r .[0].assets[0].browser_download_url)" && \
          SQLITE_FILENAME="$(curl -Ss https://sqlite.org/download.html | sed -nE "s/^PRODUCT,.*UTC,(.*),.*,.*$/\1/p")" && \
          echo "::set-output name=SQLITE_FILENAME::$SQLITE_FILENAME" && \
          echo "::set-output name=SQLITE_HASH::$(echo "$SQLITE_FILENAME" | sha256sum | cut -d ' ' -f 1)"
      - name: Setup Ninja on Windows
        if: runner.os == 'Windows'
        uses: ashutoshvarma/setup-ninja@master
      - name: Setup Ninja on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          apt-get install -y ninja-build
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.2
        with:
          key: ${{ matrix.os }}-ccache
      - name: Cache OpenSSL
        id: cache-openssl
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/openssl
          key: ${{ runner.os }}-openssl-${{ steps.query.outputs.OPENSSL_COMMIT }}
      - name: Cache mongo-c-driver
        id: cache-mongoc
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongoc
          key: ${{ runner.os }}-mongoc4-${{ steps.query.outputs.OPENSSL_COMMIT }}-${{ steps.query.outputs.MONGOC_COMMIT }}
      - name: Cache mongo-cxx-driver
        id: cache-mongocxx
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongocxx
          key: ${{ runner.os }}-mongocxx4-${{ steps.query.outputs.OPENSSL_COMMIT }}-${{ steps.query.outputs.MONGOC_COMMIT }}-${{ steps.query.outputs.MONGOCXX_COMMIT }}
      - name: Cache libuv
        id: cache-libuv
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/libuv
          key: ${{ runner.os }}-uv4-${{ steps.query.outputs.LIBUV_COMMIT }}
      - name: Cache uvw
        id: cache-uvw
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/uvw
          key: ${{ runner.os }}-uvw4-${{ steps.query.outputs.LIBUV_COMMIT }}-${{ steps.query.outputs.UVW_COMMIT }}
      - name: Cache yaml-cpp
        id: cache-yaml
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/yaml
          key: ${{ runner.os }}-yaml4-${{ steps.query.outputs.YAML_COMMIT }}
      - name: Cache SQLite3
        id: cache-sqlite
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/sqlite
          key: ${{ runner.os }}-sqlite4-${{ steps.query.outputs.SQLITE_HASH }}
      - name: Cache SOCI
        id: cache-soci
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/soci
          key: ${{ runner.os }}-soci4-${{ steps.query.outputs.SQLITE_HASH }}-${{ steps.query.outputs.SOCI_COMMIT }}
      - name: Cache Bison and Flex
        id: cache-bison
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/bison
          key: ${{ runner.os }}-bison-${{ steps.query.outputs.FLEXBISON_BUILD_ID }}
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/boost
          key: ${{ runner.os }}-boost4
      - name: Checkout OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "darktohka/openssl"
          ref: "feature/add-no-apps"
          path: "openssl"
      - name: Download Jom
        if: steps.cache-openssl.outputs.cache-hit != 'true' && runner.os == 'Windows'
        uses: suisei-cn/actions-download-file@v1
        with:
          url: "https://download.qt.io/official_releases/jom/unstable-jom.zip"
          target: openssl/
      - name: Unpack Jom
        if: steps.cache-openssl.outputs.cache-hit != 'true' && runner.os == 'Windows'
        shell: bash
        working-directory: openssl
        run: |
          unzip -qq unstable-jom.zip
      - name: Configure OpenSSL on Windows
        if: steps.cache-openssl.outputs.cache-hit != 'true' && runner.os == 'Windows'
        shell: pwsh
        working-directory: openssl
        run: |
          perl configure VC-WIN64A no-asm no-shared no-tests no-module no-dso no-legacy no-apps `
            --prefix="${{ github.workspace }}/libraries/openssl" --openssldir="${{ github.workspace }}/libraries/openssl" /FS
      - name: Configure OpenSSL on Linux
        if: steps.cache-openssl.outputs.cache-hit != 'true' && runner.os == 'Linux'
        shell: bash
        working-directory: openssl
        run: |
          perl Configure linux-x86_64 no-asm no-shared no-tests no-module no-dso no-legacy no-apps \
            --prefix="${{ github.workspace }}/libraries/openssl" --openssldir="${{ github.workspace }}/libraries/openssl"
      - name: Build and install OpenSSL on Windows
        if: steps.cache-openssl.outputs.cache-hit != 'true' && runner.os == 'Windows'
        shell: pwsh
        working-directory: openssl
        run: >
          ./jom install_sw
      - name: Build and install OpenSSL on Linux
        if: steps.cache-openssl.outputs.cache-hit != 'true' && runner.os == 'Linux'
        shell: bash
        working-directory: openssl
        run: |
          make -j$(nproc) install_sw
      - name: Cleanup OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        shell: bash
        run: |
          rm -rf openssl