name: Build Astron

on: [push, workflow_dispatch, repository_dispatch]

env:
  CMAKE_PREFIX_PATH: "${{ github.workspace }}\\libraries\\sqlite;${{ github.workspace }}\\libraries\\bison;${{ github.workspace }}\\libraries\\uvw;${{ github.workspace }}\\libraries\\boost;${{ github.workspace }}\\libraries\\openssl;${{ github.workspace }}\\libraries\\soci;${{ github.workspace }}\\libraries\\mongoc;${{ github.workspace }}\\libraries\\mongocxx;${{ github.workspace }}\\libraries\\libuv;${{ github.workspace }}\\libraries\\yaml;${{ github.workspace }}\\libraries"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            c_standard: "23"
            cxx_standard: "23"
            c_flags: ""
            cxx_flags: "/Zc:__cplusplus /EHsc"
            exe_linker_flags: "/alternatename:__imp___std_init_once_complete=__imp_InitOnceComplete /alternatename:__imp___std_init_once_begin_initialize=__imp_InitOnceBeginInitialize"
            openssl_arch: "VC-WIN64A"
            openssl_options: "/FS"
          - os: ubuntu-20.04
            c_standard: "17"
            cxx_standard: "20"
            c_flags: "-D_FORTIFY_SOURCE=2 -O3 -fstack-protector-strong -fstack-clash-protection -fPIE -Wformat -Wformat-security"
            cxx_flags: "-D_FORTIFY_SOURCE=2 -O3 -fstack-protector-strong -fstack-clash-protection -fPIE -Wformat -Wformat-security -Wno-unused-local-typedefs"
            exe_linker_flags: ""
            openssl_arch: "linux-x86_64"
            openssl_options: ""
          - os: macos-12
            c_standard: "23"
            cxx_standard: "23"
            c_flags: "-D_FORTIFY_SOURCE=2 -O3 -fstack-protector-strong -fPIE -Wformat -Wformat-security"
            cxx_flags: "-D_FORTIFY_SOURCE=2 -O3 -fstack-protector-strong -fPIE -Wformat -Wformat-security -Wno-unused-local-typedefs"
            exe_linker_flags: ""
            openssl_arch: "darwin64-x86_64"
            openssl_options: ""
    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.os }}
    steps:
      - name: Query third party commits
        id: query
        shell: bash
        run: |
          echo "::set-output name=MONGOC_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=MONGOCXX_COMMIT::$(curl -sS https://api.github.com/repos/mongodb/mongo-cxx-driver/commits/master | jq -r .sha)" && \
          echo "::set-output name=OPENSSL_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/openssl/commits/feature/add-no-apps | jq -r .sha)" && \
          echo "::set-output name=LIBUV_COMMIT::$(curl -sS https://api.github.com/repos/libuv/libuv/commits/v1.x | jq -r .sha)" && \
          echo "::set-output name=UVW_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/uvw/commits/master | jq -r .sha)" && \
          echo "::set-output name=YAML_COMMIT::$(curl -sS https://api.github.com/repos/darktohka/yaml-cpp/commits/patch-1 | jq -r .sha)" && \
          echo "::set-output name=SOCI_COMMIT::$(curl -sS https://api.github.com/repos/soci/soci/commits/master | jq -r .sha)" && \
          echo "::set-output name=MONGOC_VERSION::$(curl -sS https://api.github.com/repos/mongodb/mongo-c-driver/releases | jq -r .[0].tag_name)" && \
          FLEXBISON_REPLY="$(curl -Ss https://api.github.com/repos/lexxmark/winflexbison/releases)" && \
          echo "::set-output name=FLEXBISON_BUILD_ID::$(echo $FLEXBISON_REPLY | jq -r .[0].assets[0].id)" && \
          echo "::set-output name=FLEXBISON_LINK::$(echo $FLEXBISON_REPLY | jq -r .[0].assets[0].browser_download_url)" && \
          SQLITE_FILENAME="$(curl -Ss https://sqlite.org/download.html | sed -nE "s/^PRODUCT,.*UTC,(.*),.*,.*$/\1/p")" && \
          echo "::set-output name=SQLITE_FILENAME::$SQLITE_FILENAME" && \
          echo "::set-output name=SQLITE_HASH::$(echo "$SQLITE_FILENAME" | sha256sum | cut -d ' ' -f 1)"
      - name: Setup Visual Studio
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup Ninja on Windows
        if: runner.os == 'Windows'
        uses: ashutoshvarma/setup-ninja@master
      - name: Setup Ninja on Linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get install -y ninja-build
      - name: Setup Ninja on Mac
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install ninja
      - name: Install Bison and Flex on Mac
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install bison flex
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.2
        with:
          key: ${{ matrix.os }}-ccache
      - name: Cache OpenSSL
        id: cache-openssl
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/openssl
          key: ${{ matrix.os }}-openssl-${{ steps.query.outputs.OPENSSL_COMMIT }}
      - name: Cache mongo-c-driver
        id: cache-mongoc
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongoc
          key: ${{ matrix.os }}-mongoc-${{ steps.query.outputs.OPENSSL_COMMIT }}-${{ steps.query.outputs.MONGOC_COMMIT }}
      - name: Cache mongo-cxx-driver
        id: cache-mongocxx
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/mongocxx
          key: ${{ matrix.os }}-mongocxx-${{ steps.query.outputs.OPENSSL_COMMIT }}-${{ steps.query.outputs.MONGOC_COMMIT }}-${{ steps.query.outputs.MONGOCXX_COMMIT }}
      - name: Cache libuv
        id: cache-libuv
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/libuv
          key: ${{ matrix.os }}-libuv-${{ steps.query.outputs.LIBUV_COMMIT }}
      - name: Cache uvw
        id: cache-uvw
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/uvw
          key: ${{ matrix.os }}-uvw-${{ steps.query.outputs.LIBUV_COMMIT }}-${{ steps.query.outputs.UVW_COMMIT }}
      - name: Cache yaml-cpp
        id: cache-yaml
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/yaml
          key: ${{ matrix.os }}-yaml-${{ steps.query.outputs.YAML_COMMIT }}
      - name: Cache SQLite3
        id: cache-sqlite
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/sqlite
          key: ${{ matrix.os }}-sqlite-${{ steps.query.outputs.SQLITE_HASH }}
      - name: Cache SOCI
        id: cache-soci
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/soci
          key: ${{ matrix.os }}-soci-${{ steps.query.outputs.SQLITE_HASH }}-${{ steps.query.outputs.SOCI_COMMIT }}
      - name: Cache Bison and Flex
        if: runner.os == 'Windows'
        id: cache-bison
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/libraries/bison
          key: ${{ matrix.os }}-bison-${{ steps.query.outputs.FLEXBISON_BUILD_ID }}
      - name: Checkout libuv
        if: steps.cache-libuv.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "libuv/libuv"
          ref: "v1.x"
          path: "libuv"
      - name: Setup libuv
        if: steps.cache-libuv.outputs.cache-hit != 'true'
        working-directory: ./libuv
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/libuv" \
            -DCMAKE_C_STANDARD=${{ matrix.c_standard }} -DCMAKE_C_FLAGS="${{ matrix.c_flags }}" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLIBUV_BUILD_TESTS=OFF -DLIBUV_BUILD_BENCH=OFF .
      - name: Build and install libuv
        if: steps.cache-libuv.outputs.cache-hit != 'true'
        working-directory: ./libuv
        shell: bash
        run: |
          cmake --build . --parallel 2 --target install --config Release
      - name: Cleanup libuv
        if: steps.cache-libuv.outputs.cache-hit != 'true'
        shell: bash
        run: |
          rm -rf libuv
      - name: Checkout uvw
        if: steps.cache-uvw.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: "darktohka/uvw"
          ref: "master"
          path: "uvw"
      - name: Setup uvw
        if: steps.cache-uvw.outputs.cache-hit != 'true'
        working-directory: uvw/build
        shell: bash
        run: |
          cmake -G"Ninja" -DCMAKE_PREFIX_PATH="${{ env.CMAKE_PREFIX_PATH }}" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/libraries/uvw" \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
            -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DBUILD_UVW_SHARED_LIB=OFF -DBUILD_UVW_LIBS=ON \
            -DBUILD_TESTING=OFF -DBUILD_DOCS=OFF -DFETCH_LIBUV=OFF -DFIND_LIBUV=ON ..
      - name: Build and install uvw
        if: steps.cache-uvw.outputs.cache-hit != 'true'
        working-directory: uvw/build
        shell: bash
        run: |
          cmake --build . --parallel 2 --target install --config Release
      - name: Cleanup uvw
        if: steps.cache-uvw.outputs.cache-hit != 'true'
        shell: bash
        run: |
          rm -rf uvw